#!/bin/bash

apt-get install -y --force-yes \
    build-essential \
    curl \
    git \
    htop \
    imagemagick \
    language-pack-en \
    language-pack-es \
    libbz2-dev \
    libffi-dev \
    libglib2.0-dev \
    libjpeg-dev \
    libpq-dev \
    libpq5 \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    locales \
    openssh-client \
    openssh-server \
    python \
    python-dev \
    python-pip \
    python-setuptools \
    python-software-properties \
    python3-dev \
    tar \
    zip \
    zlib1g-dev \
    #

pip install \
    virtualenv \
    virtualenvwrapper \
    #

gem install foreman


echo <<<'
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2.7
source /usr/local/bin/virtualenvwrapper.sh
' >> ~/.bashrc

